version: '3'
services:
  StreamerHelper
    image: itgoyo/streamerhelper:v1
    volumes:
      - "/${PWD}/StreamerHelper/templates/info.json:/app/templates/info.json"
      - "/${PWD}/StreamerHelper/download:/app/download"
    restart:
        always
    dns:
        114.114.114.114
