version: '3'
services:
  StreamerHelper:
    image: itgoyo/streamerhelper:v1
    volumes:
      - "./info.json:/app/templates/info.json"
      - "./StreamerHelper/download:/app/download"
    restart:
        always
    dns:
        114.114.114.114
